services:
  hvplot:
    image: epinux/hvplotslim:latest
    build:
      context: ./docker/hvplot
    environment:
      BOKEH_ALLOW_WS_ORIGIN: 'localhost:7778,0.0.0.0:7778,192.168.0.13:7778'
      PORT: '7777'
      LOG_LEVEL: 'debug'
      BOKEH_LOG_LEVEL: 'debug'
      PYTHONUNBUFFERED: 1
      TSPLOT_DOWNLOAD: "/usr/src/app/static/Download"
      PROCESSING_ENDPOINT: 'http://192.168.0.13:8004'
    ports:
      - 7778:7777
    hostname: hvplot
    volumes:
      - ./hvplot:/usr/src/app
      - ./docker/hvplot/entrypoint.sh:/usr/src/app/entrypoint.sh
    entrypoint: /usr/src/app/entrypoint.sh
