services:
  hvplot:
    image: epinux/hvplot:latest
    build:
      context: ./docker/hvplot
    environment:
      BOKEH_ALLOW_WS_ORIGIN: 'localhost:7777'
      PORT: '7777'
      LOG_LEVEL: 'debug'
      BOKEH_LOG_LEVEL: 'debug'
      PYTHONUNBUFFERED: 1
      TSPLOT_DOWNLOAD: "/app/static/Download"
    ports:
      - 7777:7777
    hostname: hvplot
    volumes:
      - ./app:/app
      - ./docker/hvplot/entrypoint.sh:/entrypoint.sh